// Slate Early Product Test participant documents — VERBATIM from Vera's final documents
// (provided by the founder, 2026-10-10). Generated; do not edit the wording here. Any change
// needs Vera's review, professional legal review, and a new PARTICIPANT_VERSION (everyone is
// asked again). The only substitution is the version placeholder → PARTICIPANT_VERSION.

export const PARTICIPANT_VERSION = '2026-10-13'

export type ParticipantRole = 'guest' | 'worker'

export const GUEST_SHEET_MD = "### Slate Early Product Test — Guest Information\n\n**Version:** 2026-10-13\n\nSlate is testing an early version of its app with adults in New York City. Taking part is voluntary. You must be 18 or older, and you may stop at any time.\n\nThe first test is limited to:\n\n1. scanning a worker’s Slate QR code;\n2. creating or using a Slate account;\n3. reading the test information;\n4. agreeing to participate; and\n5. submitting a rating for a worker who personally served you.\n\nFollowing, shift emails, vibe reports and venue comments are not part of this first test.\n\n### What your rating does\n\nYour rating may include stars, optional tags and an optional written comment. It appears on the worker’s public profile.\n\nYour name and email address will not appear with your rating. Slate will not display a public account identifier that links your ratings together.\n\nRatings are stored by Slate and are not currently stored on a blockchain. Ratings cannot be edited after submission, but you may request deletion.\n\n### Points and tokens\n\nThe worker may receive Slate Points because of your rating. Slate Points have no cash value and cannot be sold, transferred or exchanged.\n\n$SERVE has not been issued. Slate does not promise that it will launch or that Slate Points will convert into $SERVE or anything else.\n\n### Voluntary participation and withdrawal\n\nYou may stop participating at any time. Withdrawal immediately prevents you from submitting new ratings or taking part in future test actions.\n\nWithdrawal does not automatically remove ratings you already submitted. Existing ratings remain public unless you separately request deletion.\n\n### Deletion\n\nTo request deletion, email team@slatenow.xyz from the email address on your account. Slate will verify the request and aims to process it within 30 days.\n\nAt the 30-day post-test review, Slate plans to delete test participant accounts and associated content unless you explicitly elect to remain. This is subject to necessary legal, security, audit and provider-backup retention.\n\nPreviously awarded Slate Points may remain with the worker after your rating is deleted.\n\n### Risks and limitations\n\nThis is early software. It may contain errors, interruptions or confusing screens. A submitted rating may be publicly visible until it is deleted.\n\n### Questions or concerns\n\nContact team@slatenow.xyz. If a serious privacy, identity or attribution problem occurs, Slate will stop the test, preserve relevant evidence and escalate it to the founder.\n"

export const WORKER_SHEET_MD = "### Slate Early Product Test — Worker Information\n\n**Version:** 2026-10-13\n\nSlate is testing an early version of its app with adults in New York City. Taking part is voluntary. You must be 18 or older, and you may stop at any time.\n\nThe first test focuses on whether a guest can scan your Slate QR code, sign up, understand the experience and submit a rating.\n\n### What may be public\n\nIf you participate, your Slate profile may publicly show:\n\n- your name, photo, role, bio and specialties;\n- your workplaces;\n- ratings and comments;\n- follower count;\n- Slate Points; and\n- your current venue when you are publicly marked as on shift.\n\nIndividual followers are not publicly listed. Workers may see a follower’s first name and last initial, but not the follower’s email address.\n\n### Ratings\n\nGuest ratings, tags and comments may appear on your public profile. Ratings are stored by Slate and are not currently stored on a blockchain.\n\nYou may ask Slate to review a rating that violates the Terms. A guest may request deletion of a rating they submitted.\n\n### Location and shifts\n\nStarting a shift is public and may show the venue where you are working.\n\nA location check may be used to determine whether you are near the venue. Raw coordinates are not intended to be stored. Slate may retain whether the check passed and an approximate distance internally. These checks are not proof of presence.\n\n### Points and tokens\n\nSlate Points have no cash value and cannot be sold, transferred or exchanged.\n\n$SERVE has not been issued. Slate does not promise that it will launch or that Slate Points will convert into it or anything else.\n\n### Withdrawal and visibility\n\nYou may withdraw from the early test at any time.\n\nAfter withdrawal:\n\n- you cannot start new shifts or receive new ratings or followers through the test;\n- new test activity involving your profile is blocked;\n- your public profile may be hidden;\n- your existing account and historical data are preserved;\n- your profile becomes visible again if you later accept the current worker agreement.\n\nWithdrawal does not delete your account or historical data. You may separately request deletion at team@slatenow.xyz.\n\nPreviously awarded Slate Points are not removed merely because you withdraw or a rating is deleted.\n\n### Test review and deletion\n\nThirty days after the test ends, Slate will review participant accounts and associated content. Slate plans to delete test participant accounts and associated content unless the participant explicitly elects to remain.\n\nNecessary legal, security, audit and provider-backup retention may remain.\n\n### Questions or concerns\n\nContact team@slatenow.xyz. Slate will immediately stop the test and preserve evidence if a serious privacy, identity, attribution or unauthorized-disclosure problem occurs.\n"

export const CONSENT_CARDS: Record<ParticipantRole, { title: string; paragraphs: string[]; link: string; checkbox: string }> = {
  guest: {
  "title": "Take part in Slate’s early test?",
  "paragraphs": [
    "This test is voluntary and for people 18 or older. The test is limited to scanning a worker’s QR code, signing up, agreeing to the test information, and submitting a rating.",
    "Your rating and optional comment may appear publicly on the worker’s profile without your name or email. Slate does not display a public account identifier linking your ratings together.",
    "Your rating is stored by Slate, not on a blockchain. Slate Points have no cash value, and $SERVE has not been issued.",
    "You may withdraw from future participation at any time. Existing ratings remain unless you separately request deletion. You may request deletion at team@slatenow.xyz."
  ],
  "link": "Read the full guest information sheet",
  "checkbox": "I am 18 or older, I have read the Slate Early Product Test guest information sheet, and I agree to participate."
},
  worker: {
  "title": "Take part in Slate’s early test?",
  "paragraphs": [
    "This test is voluntary and for workers 18 or older. Your profile, ratings, comments, workplaces, follower count, Slate Points and current shift venue may be publicly visible.",
    "Ratings are stored by Slate, not on a blockchain. Slate Points have no cash value, and $SERVE has not been issued.",
    "If you withdraw, future test activity is blocked and your profile may be hidden. Your account and historical data are preserved, and your profile may become visible again if you accept the current worker agreement."
  ],
  "link": "Read the full worker information sheet",
  "checkbox": "I am 18 or older, I have read the Slate Early Product Test worker information sheet, and I agree to participate."
},
}
